name: CI

on: [push]

jobs:
  build:
    name: GitHub Action for Yarn

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: build
      - uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test
