name: CI

on: [push]

jobs:
  build:
    name: GitHub Action for Yarn

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: lint
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: test
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test
      - name: build
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: build
